import css from "./Footer.module.css";

const Footer = () => {
  return (
    <footer className={css.footer}>
      <div className={css.container}>
        <p className={css.text}>
          This website was created while learning React. All information on this
          page is copied from Wikipedia or was generated by ChatGPT.
        </p>
      </div>
    </footer>
  );
};

export default Footer;
